Client::chargeProjectCredits
keboola/kbc-manage-api-php-client pull request #112
Opened 2020-09-19 08:44 UTC by ErikZigo

2020-09-22 08:41 UTC, zajca requested changes
Typo a špatná konstanta. Jinak cajk.

2020-09-22 08:41 UTC, zajca commented on tests/ProjectsTest.php
> +        $feature = self::PAY_AS_YOU_GO_CREDITS_ADMIN_FEATURE_NAME;
Tady je asi špatně const
```suggestion
        $feature = self::PAY_AS_YOU_GO_PROJECT_FEATURE_NAME;
```

2020-09-22 08:41 UTC, zajca commented on tests/ProjectsTest.php
> +    public function testCreditsCannotBeChardetToNonPaygoProject(): void
```suggestion
    public function testCreditsCannotBeChargedToNonPaygoProject(): void
```

2020-09-22 14:26 UTC, ErikZigo commented on tests/ProjectsTest.php
> +    public function testCreditsCannotBeChardetToNonPaygoProject(): void
fixed

2020-09-22 14:26 UTC, ErikZigo commented on tests/ProjectsTest.php
> +        $feature = self::PAY_AS_YOU_GO_CREDITS_ADMIN_FEATURE_NAME;
fixed

2020-09-23 07:52 UTC, zajca approved these changes
Jo testy mi přijdou cajk vypadá to, že je tam všecko. Ještě si to musím rozchodit nemám to asi nasetupované celé toho clienta.

2020-09-24 13:07 UTC, merged